# Generated by Django 3.0.8 on 2020-12-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='imagencolor1',
        ),
        migrations.RemoveField(
            model_name='color',
            name='imagencolor2',
        ),
        migrations.RemoveField(
            model_name='color',
            name='imagencolor3',
        ),
        migrations.RemoveField(
            model_name='color',
            name='imagencolor4',
        ),
        migrations.RemoveField(
            model_name='color',
            name='imagencolor5',
        ),
        migrations.AddField(
            model_name='color',
            name='state',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='Imagencolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('state', models.BooleanField(blank=True, default=True, null=True)),
                ('namecolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Color')),
            ],
        ),
    ]
