# Generated by Django 3.0.3 on 2020-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='value',
            field=models.CharField(blank=True, db_column='numvalue', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='talla',
            name='value',
            field=models.CharField(blank=True, db_column='numvalue', max_length=60, null=True),
        ),
    ]
