# Generated by Django 3.0.8 on 2021-01-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20210105_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fotoportada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fotoportadaactivo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idgenero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idmarca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idmodelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idtipoproducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idusuario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='mostrarpaginicio',
        ),
        migrations.AddField(
            model_name='talla',
            name='tallaproducto',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
