# Generated by Django 3.0.8 on 2020-08-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_producto_fotoportadaactivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='prodoferta',
            new_name='preciooferta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fechacreacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precioreal',
        ),
        migrations.AddField(
            model_name='categoria',
            name='fotocategoria1',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fotocategoria2',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fotocategoria3',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fotocategoria4',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='photo_category_product',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='preciointernet',
            field=models.IntegerField(blank=True, db_column='PrecioInternet', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precionormal',
            field=models.IntegerField(blank=True, db_column='PrecioNormal', null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fotocategoria',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
