# Generated by Django 3.0.8 on 2020-09-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20200901_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='state',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.IntegerField(blank=True, db_column='activopro', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='mostrarpaginicio',
            field=models.IntegerField(blank=True, db_column='mostrarPagInicio', null=True),
        ),
    ]
