# Generated by Django 3.0.8 on 2020-12-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20201208_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagencolor',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
