# Generated by Django 3.0.8 on 2020-08-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20200809_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fotosproducts5',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fotosproducts6',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fotosproducts7',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
