# Generated by Django 3.0.8 on 2020-11-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_city_distric_province'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distric',
            new_name='District',
        ),
    ]
