# Generated by Django 3.0.8 on 2021-01-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20210105_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stateportada',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
