# Generated by Django 3.0.8 on 2020-12-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_imagencolor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagencolor',
            name='namecolor',
        ),
        migrations.AddField(
            model_name='color',
            name='idcolor',
            field=models.ManyToManyField(to='servicios.Imagencolor'),
        ),
    ]
