# Generated by Django 3.0.8 on 2020-11-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20201124_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='statedisponible',
            new_name='tienda',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='statedisponible',
            new_name='tienda',
        ),
        migrations.AlterField(
            model_name='city',
            name='delivery',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='delivery',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='delivery',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
