# Generated by Django 3.0.8 on 2020-08-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20200810_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen_color', models.CharField(blank=True, db_column='nomColor', max_length=60, null=True)),
                ('Imagen_number_color', models.CharField(blank=True, db_column='numColor', max_length=60, null=True)),
                ('value', models.CharField(blank=True, db_column='numvalue', max_length=60, null=True)),
                ('Imagen_color_1', models.ImageField(blank=True, null=True, upload_to='colorimagen')),
                ('Imagen_color_2', models.ImageField(blank=True, null=True, upload_to='colorimagen')),
                ('Imagen_color_3', models.ImageField(blank=True, null=True, upload_to='colorimagen')),
                ('Imagen_color_4', models.ImageField(blank=True, null=True, upload_to='colorimagen')),
                ('Imagen_color_5', models.ImageField(blank=True, null=True, upload_to='colorimagen')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='fotoportada',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenidcolor',
            field=models.ManyToManyField(to='servicios.ImagenesColor'),
        ),
    ]
