# Generated by Django 3.0.8 on 2020-12-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20201208_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='idcolor',
            new_name='idimagencolor',
        ),
    ]
