# Generated by Django 3.0.8 on 2021-01-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20210105_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('fotoportada', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('estadoportada', models.BooleanField(blank=True, default=True, null=True)),
                ('portadaproducto', models.ManyToManyField(to='servicios.Producto')),
            ],
        ),
    ]
